refact: Decide API
optimizely/python-sdk pull request #314
Opened 2021-01-22 14:16 UTC by oakbani

Summary
-------
This PR refactors and fixes the decide implementation in another branch. 
**todo: reasons work. It will be cone separately**. 

Test plan
---------
- Unit Tests added. 
- Manually verified with Decide API tests in FSC

Issues
------

2021-01-22 22:39 UTC, jaeopt requested changes
Changes suggested. 
I also see some comments for previous PRs (#305, #309) not addressed yet. Can you fix them as well?

2021-01-25 13:23 UTC, oakbani commented on optimizely/optimizely.py
> +
I have already placed another check below which ensures that it must be a list when non-null

2021-01-25 13:28 UTC, oakbani commented on optimizely/optimizely.py
> +            self.logger.error(enums.Errors.INVALID_OPTIMIZELY.format('decide_all'))
it already does. Looks like github is not showing you the updated diff.

2021-01-25 14:46 UTC, oakbani commented
@jaeopt  I have tried to address all of your comments both in this PR and the rest. I am yet to take a final look on the unit tests. You may re-review all new changes besides the tests file.

2021-01-25 20:01 UTC, jaeopt requested changes
A couple of changes suggested. Other than that, all looks good.
I didn't review changes in unit tests. I'll take a look at them with your remaining fixes.

2021-01-28 16:49 UTC, oakbani commented
@jaeopt  Reasons work has been done. Unit testing is in progress. You may review reasons related work for now.

2021-01-29 01:08 UTC, jaeopt requested changes
Overall it looks good! 
Some small changes suggested.

2021-01-29 18:16 UTC, jaeopt requested changes
Looks great!
Suggested a few more tests for "reasons" validation

2021-01-29 18:16 UTC, jaeopt commented on tests/test_user_context.py
> +    def test_decide__option__include_reasons__feature_test(self):
These tests look good.
Can we add a few more tests validating "reasons" messages for:
- hit on everyone-else rule
- hit on none of the rules
- hit variation from "get_forced_variation"
- hit from "white_list"
- hit from user-profile-service
- any other important cases?

2021-02-01 17:49 UTC, jaeopt approved these changes
LGTM

2021-02-01 17:58 UTC, merged