chore(release): Preparing for 3.9.1 release
optimizely/python-sdk pull request #348
Opened 2021-07-14 21:44 UTC by The-inside-man

2021-07-14 22:00 UTC, jaeopt requested changes
master has optConfigV2 fix that is not released yet. We need release this fix from v3.9.0

2021-07-14 22:05 UTC, The-inside-man commented
> master has optConfigV2 fix that is not released yet. We need release this fix from v3.9.0

I was told to do this PR, then create a new release branch from v3.9.0 and cherrypick this commit and the fix commit once ready. FSC has a few failures so need to make some changes first.

2021-07-15 12:23 UTC, The-inside-man commented
Once merged in I will create a new branch of release V3.9.0 commit and cherry pick this and the other fix commit into the new release branch which will be what we release for the Python SDK.

2021-07-15 16:44 UTC, msohailhussain commented on optimizely/event/user_event_factory.py
> +        variation, experiment_id = None, None
update license header

2021-07-15 16:53 UTC, closed without merging