chore: prepare for release 3.11.0
optimizely/python-sdk pull request #372
Opened 2022-01-06 14:25 UTC by ozayr-zaviar

## Summary
- Prepare for release 3.11.0

2022-01-06 17:23 UTC, jaeopt requested changes
nit

2022-01-06 17:23 UTC, jaeopt commented on CHANGELOG.md
> +* Add a set of new APIs for overriding and managing user-level flag, experiment and delivery rule decisions. These methods can be used for QA and automated testing purposes. They are an extension of
Can we change the orders to [361, 365, 369]?

2022-01-10 21:22 UTC, jaeopt approved these changes
LGTM

2022-01-12 23:39 UTC, Mat001 approved these changes
lgtm

2022-01-12 23:48 UTC, merged