feat: fetch timeout made configurable
optimizely/python-sdk pull request #411
Opened 2022-11-23 15:14 UTC by ozayr-zaviar

Summary
-------
- Fetch segment timeout made configurable through `sdk_settings` option

Test plan
---------
- All unit tests and FSC should pass

2022-12-02 14:29 UTC, andrewleap-optimizely requested changes
Looks good! A couple minor suggestions.

Also can we add a test confirming the new settings get passed in appropriately?

2022-12-03 00:44 UTC, jaeopt requested changes
A suggestion to pass down timeout while initialization. Other than that, it looks good.

2022-12-03 00:44 UTC, jaeopt commented on optimizely/odp/odp_event_api_manager.py
> +    def send_odp_events(self,
What about passing the timeout value when initializing?  We do not need to send timeout for every event. It's not expected we need event-by-event control. Also a custom OdpEventApiManager can have own timeout control.

2022-12-03 00:44 UTC, jaeopt commented on optimizely/odp/odp_segment_api_manager.py
> +                       user_value: str, segments_to_check: list[str],
same here. we may keep the timeout constant locally instead of passing timeout for each api call.

2022-12-03 00:44 UTC, jaeopt commented on optimizely/odp/odp_manager.py
> +        self.event_manager.odp_event_timeout = odp_event_timeout
+1  Pass it down all the way to OdpEventApiManager and OdpSegmentApiManager?

2022-12-07 14:38 UTC, andrewleap-optimizely requested changes
Just a couple more small suggestions. Also can we add one more test for Optimizely initialization with OptimizelySdkSettings and the two new parameters?

2022-12-07 14:38 UTC, andrewleap-optimizely commented on optimizely/odp/odp_segment_api_manager.py
> +        self.timeout = timeout
```suggestion
        self.timeout = timeout or OdpSegmentApiConfig.REQUEST_TIMEOUT
```

2022-12-07 16:45 UTC, jaeopt approved these changes
LGTM

2022-12-09 14:26 UTC, andrewleap-optimizely approved these changes
lgtm

2022-12-20 06:05 UTC, merged