fix: add notification center registry
optimizely/python-sdk pull request #413
Opened 2023-01-19 19:55 UTC by andrewleap-optimizely

Summary
-------
Create a private registry of NotificationCenters for internal use.
- Remove dependence on user supplied NotificationCenter.
- Resolve issue of notifications being registered with one NotificationCenter and sent to a different one.

Test plan
---------
added tests to
- test_notification_center_registry.py
- test_optimizely.py
- test_optimizely_config.py
- test_optimizely_factory.py

Ticket
------

[FSSDK-8773](https://jira.sso.episerver.net/browse/FSSDK-8773)

2023-01-27 17:14 UTC, jaeopt requested changes
Changes look good.  I see a case when sdk_key is not provided. See my comments.

2023-01-27 17:14 UTC, jaeopt commented on optimizely/optimizely.py
> +        self.setup_odp(sdk_key or self.config_manager.get_sdk_key())
I see 2 changes related to "sdk_key" in here and in config_manager, both optional.
If none of them required, then we may have a case sdk_key is null.
As noted in my comment in config_manager, we may not need get_sdk_key in config_manager. 
We can consider "sdk_key" in optimizely from optional to required while removing the changes in config_manager.

2023-01-27 20:51 UTC, Mat001 approved these changes
Looks ok. One typo

2023-01-27 20:51 UTC, Mat001 commented on tests/test_notification_center_registry.py
> +# Copyright 2019, Optimizely
2023?

2023-02-03 18:56 UTC, jaeopt approved these changes
LGTM

2023-02-03 19:04 UTC, jaeopt commented
@andrewleap-optimizely can we keep a note about this breaking change. We should release a major version bump with this note.

2023-02-03 21:56 UTC, merged