[FSSDK-9780] Return Latest Experiment When Duplicate Keys in Config
optimizely/python-sdk pull request #430
Opened 2023-12-05 17:53 UTC by Mat001

Summary
-------

-  As a developer, I want to avoid non-deterministic return values in optimizely_get_config method so that I can anticipate the return values in my application logic.
- The problem: we have flag 1 and flag 2. We have experiment rule A with id 123 and experiment rule A with id 456 (same rule key). Flag 1 has the first experiment rule A, flag 2 has the second experiment rule A. Has a rule with the same experiment key.
We want to avoid that, so we provide a check and a warning log.

Test plan
---------
- write unit tests

Issues
------

- https://jira.sso.episerver.net/browse/FSSDK-9780

2023-12-05 18:22 UTC, jaeopt approved these changes
LGTM

2023-12-05 19:25 UTC, andrewleap-optimizely requested changes

2023-12-05 19:25 UTC, andrewleap-optimizely commented on optimizely/optimizely_config.py
> +        self.logger = logger
Where did this logger come from? (not where it was supposed to!)

2023-12-05 22:05 UTC, Mat001 commented on tests/test_optimizely_config.py
> +        with patch('optimizely.logger.SimpleLogger.warning') as mock_logger:
Ideally it'd be patching smth like: 'optimizely.optimizely_config.OptimizelyConfigService.logger'.
SimpleLogger looks a bit weird. But I'm ok if it's just for the test

2023-12-06 18:46 UTC, andrewleap-optimizely requested changes

2023-12-06 18:46 UTC, andrewleap-optimizely commented on tests/test_optimizely_config.py
> +        config_service = optimizely_config.OptimizelyConfigService(proj_conf, logger)
This is the logger module ☝️

2023-12-06 22:30 UTC, andrewleap-optimizely approved these changes
LGTM

2023-12-06 22:36 UTC, merged