[FSSDK-10763] Implement UPS request batching for decideForKeys
optimizely/python-sdk pull request #440
Opened 2024-11-13 15:51 UTC by FarhanAnjum-opti

Summary
-------
- Currently, decideForKeys loops over the list of flags and calls decide for each, which in turn calls ups. So for decideForKeys, there is two calls per flag to UPS. This PR batches UPS calls when using decideForKeys.

Test plan
---------

- Existing tests are updated to work with the new change. New tests will be added for batching.

Issues
------

-  FSSDK-10763

2024-11-20 18:45 UTC, Mat001 requested changes
Looks great! Just please cleanup old commented out pieces. Then we'll merge once done :)

2024-11-20 19:12 UTC, FarhanAnjum-opti commented on optimizely/user_profile.py
> +                # self.logger.info(message)
This was actually in java

2024-11-21 11:14 UTC, raju-opti requested changes

2024-11-21 11:14 UTC, raju-opti commented on optimizely/decision_service.py
> +                        self.user_profile_service.save(user_profile_tracker.get_user_profile().__dict__)
This will cause the user profile service to be saved for each flag key, making the batching save ineffective. This if block should be removed

2024-11-21 11:14 UTC, raju-opti commented on optimizely/optimizely.py
> +        user_profile_tracker = user_profile.UserProfileTracker(user_id, self.user_profile_service, self.logger)
should there be a `user_profile_service.load_user_profile()` call here. I suspect this could be a reason behind FSC failures

2024-11-21 11:14 UTC, raju-opti commented on optimizely/optimizely.py
> +                                                           user_profile_tracker)
the user profile should be saved here as we will remove the save from get_variation() in decision service.

2024-11-27 06:31 UTC, Mat001 approved these changes
I think it looks ok to me!

2024-11-27 12:47 UTC, raju-opti approved these changes
lgtm. two non critical comments

2024-11-27 16:24 UTC, FarhanAnjum-opti commented on optimizely/user_profile.py
> +            self.logger.warning(f'Failed to save user profile of user "{self.user_profile.user_id}" '
added error handling in case an error handler is passed

2024-11-27 16:25 UTC, FarhanAnjum-opti commented on optimizely/user_profile.py
> +            message = str(exception)
added error handling in case an error handler is passed

2024-11-27 16:27 UTC, merged